Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -238,6 +238,28 @@ jobs:
 
              echo ".env.prod created successfully"
 
+             pwd
+
+             ls -lah
+
+             echo "Checking .env.prod..."
+
+             if [ -f .env.prod ]; then
+              echo ".env.prod exists"
+              else
+              echo ".env.prod NOT FOUND"
+              exit 1
+              fi
+
+              echo "------ Last 5 lines ------"
+              tail -5 .env.prod
+
+              echo "------ ECR_IMAGE ------"
+              cat .env.prod | grep ECR_IMAGE || true
+
+              echo "------ docker-compose ------"
+              cat docker-compose.prod.yml | grep ECR_IMAGE || true
+
             echo
             echo "======================================="
             echo "Docker Login"
